#!/system/bin/sh
PROFILE="${1:-balanced}"
echo "[op9pro] Applying: $PROFILE"
w() { [ -f "$1" ] && echo "$2" > "$1" 2>/dev/null; }
case "$PROFILE" in
performance)
w /sys/devices/system/cpu/cpufreq/policy0/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/rate_limit_us 500
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/hispeed_freq 1612800
w /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq 691200
w /sys/devices/system/cpu/cpufreq/policy4/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/rate_limit_us 500
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/hispeed_freq 2131200
w /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq 710400
w /sys/devices/system/cpu/cpufreq/policy7/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/rate_limit_us 500
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/hispeed_freq 2649600
w /sys/devices/system/cpu/cpufreq/policy7/scaling_min_freq 844800
w /proc/sys/kernel/sched_upmigrate 80
w /proc/sys/kernel/sched_downmigrate 60
w /proc/sys/kernel/sched_boost 1
w /proc/sys/vm/swappiness 60
w /proc/sys/vm/dirty_ratio 30
w /proc/sys/vm/dirty_background_ratio 10
w /proc/sys/vm/dirty_expire_centisecs 3000
w /proc/sys/vm/dirty_writeback_centisecs 500
w /proc/sys/vm/vfs_cache_pressure 50
w /proc/sys/vm/page-cluster 0
w /proc/sys/vm/min_free_kbytes 16384
w /sys/block/sda/queue/scheduler mq-deadline
w /sys/block/sda/queue/read_ahead_kb 512
w /sys/block/sda/queue/nr_requests 256
w /sys/block/sda/queue/iostats 0
w /sys/block/sda/queue/add_random 0
w /sys/block/sda/queue/rq_affinity 2
w /sys/block/sdb/queue/scheduler mq-deadline
w /sys/block/sdb/queue/read_ahead_kb 512
w /sys/block/sdb/queue/iostats 0
w /proc/sys/net/core/rmem_max 8388608
w /proc/sys/net/core/wmem_max 8388608
w /proc/sys/net/ipv4/tcp_fastopen 3
w /proc/sys/net/ipv4/tcp_keepalive_time 300
w /proc/sys/net/ipv4/tcp_timestamps 1
w /proc/sys/net/ipv4/tcp_sack 1
w /proc/sys/net/ipv4/tcp_window_scaling 1
w /proc/sys/net/core/netdev_budget 600
w /proc/sys/net/core/netdev_max_backlog 5000
w /sys/module/workqueue/parameters/power_efficient N
w /sys/class/kgsl/kgsl-3d0/default_pwrlevel 0
w /sys/class/kgsl/kgsl-3d0/force_clk_on 1
w /sys/class/kgsl/kgsl-3d0/idle_timer 10000
w /sys/class/kgsl/kgsl-3d0/throttling 0
;;
battery)
w /sys/devices/system/cpu/cpufreq/policy0/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/rate_limit_us 2000
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/hispeed_freq 1017600
w /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq 300000
w /sys/devices/system/cpu/cpufreq/policy4/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/rate_limit_us 2000
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/hispeed_freq 1267200
w /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq 710400
w /sys/devices/system/cpu/cpufreq/policy7/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/rate_limit_us 4000
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/hispeed_freq 1574400
w /sys/devices/system/cpu/cpufreq/policy7/scaling_min_freq 844800
w /proc/sys/kernel/sched_upmigrate 95
w /proc/sys/kernel/sched_downmigrate 85
w /proc/sys/kernel/sched_boost 0
w /proc/sys/vm/swappiness 150
w /proc/sys/vm/dirty_ratio 10
w /proc/sys/vm/dirty_background_ratio 3
w /proc/sys/vm/dirty_expire_centisecs 1000
w /proc/sys/vm/dirty_writeback_centisecs 300
w /proc/sys/vm/vfs_cache_pressure 150
w /proc/sys/vm/page-cluster 3
w /proc/sys/vm/min_free_kbytes 8192
w /sys/block/sda/queue/scheduler bfq
w /sys/block/sda/queue/read_ahead_kb 128
w /sys/block/sda/queue/nr_requests 64
w /sys/block/sda/queue/iostats 0
w /sys/block/sda/queue/add_random 0
w /sys/block/sda/queue/rq_affinity 1
w /sys/block/sdb/queue/scheduler bfq
w /sys/block/sdb/queue/read_ahead_kb 128
w /sys/block/sdb/queue/iostats 0
w /proc/sys/net/core/rmem_max 2097152
w /proc/sys/net/core/wmem_max 2097152
w /proc/sys/net/ipv4/tcp_fastopen 3
w /proc/sys/net/ipv4/tcp_keepalive_time 1200
w /proc/sys/net/core/netdev_budget 150
w /proc/sys/net/core/netdev_max_backlog 1000
w /sys/module/workqueue/parameters/power_efficient Y
w /sys/class/kgsl/kgsl-3d0/default_pwrlevel 6
w /sys/class/kgsl/kgsl-3d0/force_clk_on 0
w /sys/class/kgsl/kgsl-3d0/idle_timer 32
w /sys/class/kgsl/kgsl-3d0/throttling 1
;;
*)
w /sys/devices/system/cpu/cpufreq/policy0/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/rate_limit_us 1000
w /sys/devices/system/cpu/cpufreq/policy0/schedutil/hispeed_freq 1324800
w /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq 300000
w /sys/devices/system/cpu/cpufreq/policy4/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/rate_limit_us 1000
w /sys/devices/system/cpu/cpufreq/policy4/schedutil/hispeed_freq 1766400
w /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq 710400
w /sys/devices/system/cpu/cpufreq/policy7/scaling_governor schedutil
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/rate_limit_us 1000
w /sys/devices/system/cpu/cpufreq/policy7/schedutil/hispeed_freq 2188800
w /sys/devices/system/cpu/cpufreq/policy7/scaling_min_freq 844800
w /proc/sys/kernel/sched_upmigrate 90
w /proc/sys/kernel/sched_downmigrate 75
w /proc/sys/kernel/sched_boost 0
w /proc/sys/vm/swappiness 100
w /proc/sys/vm/dirty_ratio 20
w /proc/sys/vm/dirty_background_ratio 5
w /proc/sys/vm/dirty_expire_centisecs 2000
w /proc/sys/vm/dirty_writeback_centisecs 500
w /proc/sys/vm/vfs_cache_pressure 100
w /proc/sys/vm/page-cluster 0
w /proc/sys/vm/min_free_kbytes 11584
w /sys/block/sda/queue/scheduler bfq
w /sys/block/sda/queue/read_ahead_kb 256
w /sys/block/sda/queue/nr_requests 128
w /sys/block/sda/queue/iostats 0
w /sys/block/sda/queue/add_random 0
w /sys/block/sda/queue/rq_affinity 1
w /sys/block/sdb/queue/scheduler bfq
w /sys/block/sdb/queue/read_ahead_kb 256
w /sys/block/sdb/queue/iostats 0
w /proc/sys/net/core/rmem_max 4194304
w /proc/sys/net/core/wmem_max 4194304
w /proc/sys/net/ipv4/tcp_fastopen 3
w /proc/sys/net/ipv4/tcp_keepalive_time 600
w /proc/sys/net/core/netdev_budget 300
w /proc/sys/net/core/netdev_max_backlog 2500
w /sys/module/workqueue/parameters/power_efficient N
w /sys/class/kgsl/kgsl-3d0/default_pwrlevel 4
w /sys/class/kgsl/kgsl-3d0/force_clk_on 0
w /sys/class/kgsl/kgsl-3d0/idle_timer 64
w /sys/class/kgsl/kgsl-3d0/throttling 1
;;
esac
echo "[op9pro] Done: $PROFILE"
